# Site/SEO settings
email: fazaalmv@gmail.com
baseurl: ""
paginate: 12
paginate_path: "/page/:num"
permalink: /:year/:month/:day/:title/
google_analytics:

name: Hussain Fazaal
title: Travel ðŸ–ï¸
description: >
  This is my travel blog documenting my travels in Malaysia
url: http://travel.fazaal.com
twitter_username: fazofazaal
default_img: /assets/images/seo.jpg
social:
  - name: twitter
    url: https://twitter.com/fazofazaal
  - name: instagram
    url: https://www.instagram.com/fazofazaal/
  - name: linkedin
    url: https://www.linkedin.com/in/hussainfazaal/
  - name: github
    url: https://github.com/fazofazaal
  - name: codepen
    url: https://codepen.io/fazofazaal/

# Contact settings
contact_img: /assets/images/handshake.jpg
formcarry: https://formcarry.com/s/HkIo0nMb7

# Disqus settings
disqus: test-apkdzgmqhj

# MailChimp settings
mailchimp_action: https://samesies.us17.list-manage.com/subscribe/post-json?u=66ddf555dab480e6a8606430b&amp;id=89b3ee034f
mailchimp_input: b_66ddf555dab480e6a8606430b_89b3ee034f

# Author settings
author:
  - name: Hussain Fazaal
    bio: I'm a Software Engineering with Multimedia undergrad in Limkokwing University of Creative Technology, Malaysia hailing from Maldives. I code, design and illustrate. I also had stint at a band called TissueFace as it's bassist.
    url: http://fazaal.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
